// Venue database, workstreams, and master abstracts — content only, no logic.
const STATUSES = ["watching","shortlisted","drafting","submitted","under review","accepted","rejected","registered","presented","missed","skipped"];
const TIERS = {1:"Tier 1 · SDT & motivation core",2:"Tier 2 · Education research & EdTech",3:"Tier 3 · EDAS / engineering-ed (indexed)",4:"Journal targets · rolling submissions"};
const WS={
 1:{name:"W1 · Bibliometric + TCM-ADO (RQ1)",note:"Field-mapping / review paper. Currently under review at CHB — these are the venues for the revision's next home if needed, plus motivation-community conferences where a field-map talk lands well."},
 2:{name:"W2 · Structured Autonomy RCT (RQ2)",note:"Results arrive after the Dec 2026 analysis — venues with deadlines before that can only take the framework/WIP version, never findings. Results-ready targets are the ones with deadlines from Dec 2026 onward, plus the journals."},
 3:{name:"W3 · 3C systemic complacency paper (RQ3)",note:"Higher-education policy & management audience — India management academia and higher-ed policy journals, not the EdTech circuit."},
 4:{name:"W4 · µLearn case study (RQ4)",note:"Data from Sep 2026. Peer-learning, CSCL, and gamification venues; case-study-friendly journals."}
};
const SEED = [
 // ---- Tier 3: from the user's EDAS export (open now) ----
 {id:"icet26",sub:"portal",subUrl:"https://edas.info/",subNote:"Submit via EDAS (your account: deepusnath@gmail.com, #2596293)",fits:[2, 4],acr:"ICET 2026",name:"12th Int'l Conf. on Education and Technology",city:"Malang, Indonesia",event:"2026-10-15",dl:"2026-08-13",approx:true,tier:3,src:"EDAS export",url:"https://edas.info/listConferencesCFP.php",why:"Most direct fit in your EDAS list — education + technology, e-learning tracks. Natural home for SDT-in-EdTech empirical work.",status:"shortlisted",notes:""},
 {id:"icastss26",sub:"portal",subUrl:"https://edas.info/",subNote:"Submit via EDAS (your account: deepusnath@gmail.com, #2596293)",fits:[3, 4],acr:"iCAST-SS 2026",name:"Int'l Conf. on Applied Science & Technology — Social Sciences",city:"Surabaya, Indonesia",event:"2026-10-09",dl:"2026-08-23",approx:true,tier:3,src:"EDAS export",url:"https://edas.info/listConferencesCFP.php",why:"Online-education, social & behavioral science tracks — fits SDT survey/intervention studies.",status:"watching",notes:""},
 {id:"etecom26",sub:"portal",subUrl:"https://edas.info/",subNote:"Submit via EDAS (your account: deepusnath@gmail.com, #2596293)",fits:[2],acr:"ETECOM 2026",name:"Int'l Conf. on Emerging Trends in Engineering and Computing",city:"Paris, France (hybrid)",event:"2026-10-26",dl:"2026-08-27",approx:true,tier:3,src:"EDAS export",url:"https://edas.info/listConferencesCFP.php",why:"Online-education track; hybrid format keeps travel cost down.",status:"watching",notes:""},
 {id:"ideahci27",sub:"portal",subUrl:"https://edas.info/",subNote:"Submit via EDAS (your account: deepusnath@gmail.com, #2596293)",fits:[4],acr:"IDEA HCI 2027",name:"Int'l Conf. on Design, AI Generative, UI/UX and HCI",city:"Indonesia",event:"2027-02-08",dl:"2026-09-08",approx:true,tier:3,src:"EDAS export",url:"https://edas.info/listConferencesCFP.php",why:"Motivation-aware UX angle: SDT is the dominant framework for engagement in HCI. Deadline range Aug 8 – Sep 8 in EDAS.",status:"watching",notes:""},
 {id:"iceed26",sub:"portal",subUrl:"https://edas.info/",subNote:"Submit via EDAS (your account: deepusnath@gmail.com, #2596293)",fits:[2],acr:"ICEED 2026",name:"IEEE 15th Int'l Conf. on Engineering Education",city:"Kanazawa, Japan",event:"2026-11-25",dl:"2026-10-01",approx:true,tier:3,src:"EDAS export",url:"https://edas.info/listConferencesCFP.php",why:"IEEE engineering-education venue — strong fit for SDT applied to engineering learners; Xplore-indexed.",status:"shortlisted",notes:""},
 {id:"dasa26",sub:"portal",subUrl:"https://edas.info/",subNote:"Submit via EDAS (your account: deepusnath@gmail.com, #2596293)",fits:[3],acr:"DASA'26",name:"Int'l Conf. on Decision Aid Sciences and Applications",city:"Bangkok, Thailand",event:"2026-12-27",dl:"2026-10-02",approx:true,tier:3,src:"EDAS export",url:"https://edas.info/listConferencesCFP.php",why:"Explicit online-education and social & behavioral science areas in its CFP.",status:"watching",notes:""},
 {id:"ietbhec27",sub:"portal",subUrl:"https://edas.info/",subNote:"Submit via EDAS (your account: deepusnath@gmail.com, #2596293)",fits:[2, 3],acr:"IETBHEC'27",name:"5th Int'l Engineering, Technology, Business and Health Education Conf.",city:"Singapore",event:"2027-02-25",dl:"2026-12-15",approx:true,tier:3,src:"EDAS export",url:"https://edas.info/listConferencesCFP.php",why:"Education-centered multi-disciplinary venue; Singapore is an easy trip from Kerala.",status:"shortlisted",notes:""},
 {id:"iiphdw27",sub:"portal",subUrl:"https://edas.info/",subNote:"Submit via EDAS (your account: deepusnath@gmail.com, #2596293)",fits:[1, 2, 3, 4],acr:"IIPhDW'27",name:"Int'l Interdisciplinary PhD Workshop",city:"Wismar, Germany",event:"2027-05-05",dl:"2026-12-01",approx:true,tier:3,src:"EDAS export",url:"https://edas.info/listConferencesCFP.php",why:"Built for doctoral students — feedback on your PhD design itself, not just findings.",status:"shortlisted",notes:""},
 {id:"isec27",sub:"portal",subUrl:"https://edas.info/",subNote:"Submit via EDAS (your account: deepusnath@gmail.com, #2596293)",fits:[2],acr:"ISEC'27",name:"IEEE Integrated STEM Education Conference",city:"Baltimore, USA",event:"2027-03-12",dl:"2027-01-15",approx:true,tier:3,src:"EDAS export",url:"https://edas.info/listConferencesCFP.php",why:"IEEE STEM-education flagship on the US east coast; motivation papers are a staple here.",status:"watching",notes:""},
 {id:"technova27",sub:"portal",subUrl:"https://edas.info/",subNote:"Submit via EDAS (your account: deepusnath@gmail.com, #2596293)",fits:[2, 4],acr:"TECHNOVA-GRACE 2027",name:"Int'l Graduate Conf. on Technology, Computing and Advanced Engineering",city:"Virtual",event:"2027-08-04",dl:"2026-09-15",approx:true,tier:3,src:"EDAS export",url:"https://edas.info/listConferencesCFP.php",why:"Graduate conference, fully virtual — zero-cost reps for early-stage chapters.",status:"watching",notes:""},
 // ---- India management/higher-ed policy (3C paper venues) ----
 {id:"paniim26",sub:"portal",subUrl:"https://conf.iimshillong.ac.in/paniim2026/",subNote:"Submit through the official portal — confirm the exact route on the CFP page",fits:[3],acr:"PAN-IIM WMC 2026",name:"11th PAN-IIM World Management Conference",city:"IIM Shillong, India (hybrid)",event:"2026-11-27",dl:"2026-08-20",approx:false,tier:2,src:"Web research",url:"https://paniim2026.iimshillong.ac.in/",why:"3C paper target — Economics & Public Policy track; selected full papers considered for ABDC/Scopus journals. Notification Sep 15; registration Sep 18–Oct 20 (₹5,000+GST research scholars).",status:"drafting",notes:"Submission-ready docx prepared 11 Aug (3C-Framework-PANIIM-WMC2026.docx). Needs: co-author sign-off, similarity check, Nidhi email fix."},
 {id:"iherc26",fits:[3],acr:"IHERC 2026",name:"India Higher Education Research Conference",city:"New Delhi, India",event:"2026-12-26",dl:null,approx:true,tier:2,src:"Research deck (Aug 2026)",url:"",why:"Named in the August 2026 progress deck as backup venue for the 3C paper — CFP and deadline still to verify.",status:"watching",notes:""},
 // ---- Tier 2: global education research & EdTech ----
 {id:"inted27",sub:"portal",subUrl:"https://iated.org/inted/",subNote:"Submit through the official portal — confirm the exact route on the CFP page",fits:[2, 3, 4],acr:"INTED2027",name:"21st Int'l Technology, Education and Development Conference",city:"Valencia, Spain",event:"2027-03-09",dl:"2026-11-26",approx:true,tier:2,src:"Web research",url:"https://iated.org/inted/",why:"IATED's spring venue: education + technology, very SDT-friendly, high acceptance — good momentum builder. Abstracts open ~autumn 2026.",status:"shortlisted",notes:""},
 {id:"edulearn27",sub:"portal",subUrl:"https://iated.org/edulearn/",subNote:"Submit through the official portal — confirm the exact route on the CFP page",fits:[2, 4],acr:"EDULEARN27",name:"19th Int'l Conf. on Education and New Learning Technologies",city:"Palma, Spain",event:"2027-06-30",dl:"2027-03-25",approx:true,tier:2,src:"Web research",url:"https://iated.org/edulearn/",why:"IATED summer edition — same profile as INTED, later cycle.",status:"watching",notes:""},
 {id:"educon27",sub:"portal",subUrl:"https://educon-conference.org/",subNote:"Submit through the official portal — confirm the exact route on the CFP page",fits:[2],acr:"EDUCON 2027",name:"IEEE Global Engineering Education Conference",city:"Timişoara, Romania",event:"2027-04-20",dl:"2026-10-01",approx:true,tier:2,src:"Web research",url:"https://educon-conference.org/",why:"IEEE Education Society flagship for Region 8. 2026 cycle's abstract deadline was late Sept — expect the same; watch now.",status:"shortlisted",notes:""},
 {id:"fie27",sub:"portal",subUrl:"https://fie-conference.org/",subNote:"Submit through the official portal — confirm the exact route on the CFP page",fits:[2],acr:"FIE 2027",name:"IEEE Frontiers in Education Conference",city:"North America (TBA)",event:"2027-10-15",dl:"2027-01-26",approx:true,tier:2,src:"Web research",url:"https://fie-conference.org/",why:"Premier engineering-education research venue; motivation/SDT work is core FIE territory. Abstracts ~late Jan.",status:"watching",notes:""},
 {id:"lak27",sub:"portal",subUrl:"https://www.solaresearch.org/events/lak/lak27/",subNote:"Submit through the official portal — confirm the exact route on the CFP page",fits:[1, 2, 4],acr:"LAK27",name:"17th Int'l Learning Analytics & Knowledge Conference",city:"TBA",event:"2027-03-15",dl:"2026-10-12",approx:true,tier:2,src:"Web research",url:"https://www.solaresearch.org/events/lak/lak27/",why:"If your SDT work touches trace data, dashboards, or engagement analytics, LAK is the top-tier target. Full-paper deadline historically ~mid-Oct.",status:"watching",notes:""},
 {id:"site27",sub:"portal",subUrl:"https://site.aace.org/conf/",subNote:"Submit through the official portal — confirm the exact route on the CFP page",fits:[2],acr:"SITE 2027",name:"Society for IT & Teacher Education 38th Annual",city:"Nashville, USA",event:"2027-03-15",dl:"2026-12-18",approx:true,tier:2,src:"Web research",url:"https://site.aace.org/conf/",why:"Teacher-education + technology; CFP opens 26 Oct 2026.",status:"watching",notes:""},
 {id:"aied27",sub:"portal",subUrl:"https://iaied.org/",subNote:"Submit through the official portal — confirm the exact route on the CFP page",fits:[1, 2, 4],acr:"AIED 2027",name:"Int'l Conf. on Artificial Intelligence in Education",city:"TBA",event:"2027-07-15",dl:"2027-02-01",approx:true,tier:2,src:"Web research",url:"https://iaied.org/",why:"Top AI-in-education venue; SDT-informed adaptive/motivational systems fit the main track.",status:"watching",notes:""},
 {id:"isls27",sub:"portal",subUrl:"https://www.isls.org/",subNote:"Submit through the official portal — confirm the exact route on the CFP page",fits:[2, 4],acr:"ISLS 2027",name:"Int'l Society of the Learning Sciences Annual Meeting",city:"TBA",event:"2027-06-15",dl:"2026-11-15",approx:true,tier:2,src:"Web research",url:"https://www.isls.org/",why:"Learning-sciences flagship (CSCL + ICLS); submissions typically due mid-November.",status:"watching",notes:""},
 {id:"aect27",sub:"portal",subUrl:"https://www.aect.org/",subNote:"Submit through the official portal — confirm the exact route on the CFP page",fits:[2, 4],acr:"AECT 2027",name:"AECT International Convention",city:"USA (TBA)",event:"2027-10-15",dl:"2027-02-16",approx:true,tier:2,src:"Web research",url:"https://www.aect.org/",why:"Educational communications & technology; 2026 proposals closed Feb — same window expected for 2027.",status:"watching",notes:""},
 {id:"iceri26",sub:"portal",subUrl:"https://iated.org/iceri/",subNote:"Submit through the official portal — confirm the exact route on the CFP page",fits:[2, 3, 4],acr:"ICERI2026",name:"19th Int'l Conf. of Education, Research and Innovation",city:"Seville, Spain",event:"2026-11-09",dl:"2026-07-23",approx:false,tier:2,src:"Web research",url:"https://iated.org/iceri/",why:"Extended abstract deadline passed 23 Jul 2026 — but IATED often accepts late/virtual submissions; one email is worth it if you want a 2026 slot.",status:"missed",notes:""},
 {id:"tale26",sub:"portal",subUrl:"https://tale-conference.org/2026",subNote:"Submit through the official portal — confirm the exact route on the CFP page",fits:[2],acr:"TALE 2026",name:"IEEE Int'l Conf. on Teaching, Assessment and Learning for Engineering",city:"Pattaya, Thailand",event:"2026-12-02",dl:"2026-08-02",approx:false,tier:2,src:"EDAS + web",url:"https://tale-conference.org/2026",why:"Closed 2 Aug 2026 (extended). Flagship Asia-Pacific engineering-education venue — put TALE 2027 on the watchlist now.",status:"missed",notes:""},
 // ---- Tier 1: SDT & motivation core ----
 {id:"aera27",sub:"portal",subUrl:"https://www.aera.net/Events-Meetings/Annual-Meeting",subNote:"Submit through the official portal — confirm the exact route on the CFP page",fits:[1, 2, 4],acr:"AERA 2027",name:"AERA Annual Meeting — incl. Motivation in Education SIG",city:"Toronto, Canada",event:"2027-04-14",dl:"2026-07-24",approx:false,tier:1,src:"Web research",url:"https://www.aera.net/Events-Meetings/Annual-Meeting",why:"The biggest education-research meeting; closed 24 Jul 2026. Attend anyway if useful; the 2028 call opens ~May 2027 — the scout must catch it.",status:"missed",notes:""},
 {id:"earli27",sub:"portal",subUrl:"https://www.earli.org/",subNote:"Submit through the official portal — confirm the exact route on the CFP page",fits:[1, 2, 4],acr:"EARLI 2027",name:"20th Biennial EARLI Conference",city:"Europe (TBA)",event:"2027-08-20",dl:"2026-11-30",approx:true,tier:1,src:"Web research",url:"https://www.earli.org/",why:"Europe's premier learning & instruction conference; SIG 8 (Motivation & Emotion) is the SDT crowd's home. Submissions expected late 2026.",status:"shortlisted",notes:""},
 {id:"icm28",sub:"portal",subUrl:"http://motivation-emotion.eu/",subNote:"Submit through the official portal — confirm the exact route on the CFP page",fits:[1, 2, 4],acr:"ICM 2028",name:"20th Int'l Conference on Motivation (EARLI SIG 8)",city:"TBA",event:"2028-06-15",dl:"2028-01-15",approx:true,tier:1,src:"Web research",url:"http://motivation-emotion.eu/",why:"THE motivation conference. ICM 2026 (Lisbon) just passed — biennial, so 2028 is next. Watchlist item with high priority.",status:"watching",notes:""},
 {id:"sdtnext",sub:"portal",subUrl:"https://selfdeterminationtheory.org/conferences/",subNote:"Submit through the official portal — confirm the exact route on the CFP page",fits:[1, 2, 3, 4],acr:"SDT Int'l Conf. (10th)",name:"International Self-Determination Theory Conference",city:"TBA (~2029)",event:"2029-06-15",dl:"2028-10-01",approx:true,tier:1,src:"Web research",url:"https://selfdeterminationtheory.org/conferences/",why:"Your home conference. 9th edition just ran in Geneva (Jul 2026, ~triennial). Follow CSDT announcements; abstract windows open ~9 months out.",status:"watching",notes:""},
 {id:"ssm27",sub:"portal",subUrl:"https://www.thessm.org/",subNote:"Submit through the official portal — confirm the exact route on the CFP page",fits:[1, 2],acr:"SSM 2027",name:"Society for the Study of Motivation Annual Conference",city:"USA (with APS, TBA)",event:"2027-05-20",dl:"2027-01-15",approx:true,tier:1,src:"Web research",url:"https://www.thessm.org/",why:"Motivation-science society meeting co-located with APS — strong theory audience for SDT work.",status:"watching",notes:""},
 // ---- Journal targets ----
 {id:"j-chb",sub:"portal",subNote:"Revision goes through the journal's existing Editorial Manager record",fits:[1],kind:"journal",acr:"CHB",name:"Computers in Human Behavior (Elsevier)",city:"Journal · Q1, ABDC-A",event:null,dl:null,approx:false,tier:4,src:"Research deck",url:"https://www.sciencedirect.com/journal/computers-in-human-behavior",why:"W1 bibliometric paper is UNDER REVIEW here — revising on journal feedback.",status:"under review",notes:""},
 {id:"j-heff",sub:"portal",subNote:"Submit via the journal's online submission system (linked from the homepage)",fits:[3],kind:"journal",acr:"HEFF",name:"Higher Education for the Future (SAGE)",city:"Journal · Scopus",event:null,dl:null,approx:false,tier:4,src:"Research deck",url:"https://journals.sagepub.com/home/hef",why:"Primary journal target for the 3C paper per the Aug 2026 progress deck — higher-ed policy and practice, India-context friendly.",status:"shortlisted",notes:""},
 {id:"j-cae",sub:"portal",subNote:"Submit via the journal's online submission system (linked from the homepage)",fits:[1,2,4],kind:"journal",acr:"C&E",name:"Computers & Education (Elsevier)",city:"Journal · Q1",event:null,dl:null,approx:false,tier:4,src:"Curated",url:"https://www.sciencedirect.com/journal/computers-and-education",why:"Top EdTech empirical venue — strong fit for the RCT results paper and the µLearn case study.",status:"watching",notes:""},
 {id:"j-ihe",sub:"portal",subNote:"Submit via the journal's online submission system (linked from the homepage)",fits:[2,4],kind:"journal",acr:"I&HE",name:"The Internet and Higher Education (Elsevier)",city:"Journal · Q1",event:null,dl:null,approx:false,tier:4,src:"Curated",url:"https://www.sciencedirect.com/journal/the-internet-and-higher-education",why:"Online higher-ed focus; fits structured autonomy in self-directed online learning.",status:"watching",notes:""},
 {id:"j-motem",sub:"portal",subNote:"Submit via the journal's online submission system (linked from the homepage)",fits:[2,4],kind:"journal",acr:"M&E",name:"Motivation and Emotion (Springer)",city:"Journal · SDT home turf",event:null,dl:null,approx:false,tier:4,src:"Curated",url:"https://link.springer.com/journal/11031",why:"Core motivation-science journal — SDT-native audience for the RCT mediation model.",status:"watching",notes:""},
 {id:"j-lai",sub:"portal",subNote:"Submit via the journal's online submission system (linked from the homepage)",fits:[2],kind:"journal",acr:"L&I",name:"Learning and Instruction (Elsevier)",city:"Journal · Q1",event:null,dl:null,approx:false,tier:4,src:"Curated",url:"https://www.sciencedirect.com/journal/learning-and-instruction",why:"Premier European learning-research journal (EARLI); rigorous experimental motivation work fits.",status:"watching",notes:""},
 {id:"j-bjet",sub:"portal",subNote:"Submit via the journal's online submission system (linked from the homepage)",fits:[2,4],kind:"journal",acr:"BJET",name:"British Journal of Educational Technology (Wiley)",city:"Journal · Q1",event:null,dl:null,approx:false,tier:4,src:"Curated",url:"https://bera-journals.onlinelibrary.wiley.com/journal/14678535",why:"EdTech breadth with design-oriented empirical work — good fit for gamification-as-scaffolding.",status:"watching",notes:""},
 {id:"j-ijcscl",sub:"portal",subNote:"Submit via the journal's online submission system (linked from the homepage)",fits:[4],kind:"journal",acr:"ijCSCL",name:"Intl. Journal of Computer-Supported Collaborative Learning (Springer)",city:"Journal · Q1",event:null,dl:null,approx:false,tier:4,src:"Curated",url:"https://link.springer.com/journal/11412",why:"Peer-learning community mechanisms are exactly ijCSCL territory for the µLearn case study.",status:"watching",notes:""},
 {id:"j-heq",sub:"portal",subNote:"Submit via the journal's online submission system (linked from the homepage)",fits:[3],kind:"journal",acr:"HEQ",name:"Higher Education Quarterly (Wiley)",city:"Journal · Q1",event:null,dl:null,approx:false,tier:4,src:"Curated",url:"https://onlinelibrary.wiley.com/journal/14682273",why:"Higher-ed governance and policy critique — alternative home for the 3C framework.",status:"watching",notes:""},
 {id:"j-jcal",sub:"portal",subNote:"Submit via the journal's online submission system (linked from the homepage)",fits:[2,4],kind:"journal",acr:"JCAL",name:"Journal of Computer Assisted Learning (Wiley)",city:"Journal · Q1",event:null,dl:null,approx:false,tier:4,src:"Curated",url:"https://onlinelibrary.wiley.com/journal/13652729",why:"Solid mid-tier option for either empirical study if Q1 first choices bounce.",status:"watching",notes:""}
];

// ---- Default researcher profile (editable in-app; this is the seed) ----
const DEFAULT_PROFILE={
 name:"Deepu S. Nath",
 headline:"PhD Research Scholar, Amrita School of Business, Bangalore (Reg. BL.BU.D.MGT18002) \u00b7 deepu@fayausa.com \u00b7 Kerala, India (IST)",
 guidance:"Guide: Prof. Angan Sen Gupta (ASB Bangalore) \u00b7 Co-guide: Prof. Priya Gupta (ASB Bangalore) \u00b7 Doctoral committee: Prof. Nava Subramanium (ASB Coimbatore) \u00b7 Prof. Jayashankar Prasad (Director, CMD, Government of Kerala)",
 thesis:"Advancing Self-Determination Theory through Gamified Learning Ecosystems",
 thesisDesc:"How gamification and structured autonomy can support the satisfaction of basic psychological needs and move learners from externally regulated participation toward autonomous, internalised, sustained motivation.",
 chain:["Gamification + Structured Autonomy","Need satisfaction","Internalised motivation","Sustained self-determined behaviour"],
 roadmap:"Sep 2026 \u00b5Learn case-study data \u00b7 Oct experiment launch + baseline/midpoint \u00b7 Nov intervention completes, final data \u00b7 Dec analysis, validation, paper writing. In parallel: CHB revision + 3C journal preparation. Field-season rule: results papers target deadlines from Dec 2026 onward; WIP/framework papers can go anytime.",
 record:"CESI 2025, New Delhi (Dec 5\u20137): presented \u201cSelf-Determination Theory in Large-Scale Peer Learning Ecosystems\u201d \u2014 SEM, n=207. SDT2026, Geneva (Jun 30\u2013Jul 3): participated; connected with Prof. Richard Ryan (ongoing guidance; \u00b5Learn as longitudinal SDT test bed).",
 corr:"Deepu S. Nath (deepu@fayausa.com), Amrita School of Business, Bangalore, India",
 workstreams:[
 {w:1,label:"W1 \u00b7 Map the field",short:"Bibliometric + TCM-ADO analysis of 971 peer-reviewed articles (RQ1)",tag:"under review",tagCls:"good",desc:"\u201cGamification in learning and work motivation through the lens of SDT\u201d \u2014 submitted to Computers in Human Behavior; now being refined on journal feedback.",matchNote:"Field-mapping / review paper. Under review at CHB \u2014 venues here are for the next home if needed, plus motivation-community conferences where a field-map talk lands well.",
  authors:"Deepu S. Nath et al.",title:"Gamification in Learning and Work Motivation through the Lens of Self-Determination Theory: A Bibliometric and TCM-ADO Analysis",
  abs:"Gamification research has grown rapidly, yet its motivational foundations remain unevenly theorised. This study maps how gamification has been examined through the lens of Self-Determination Theory (SDT) across learning and workplace contexts. Screening 971 peer-reviewed articles, we combine bibliometric analysis with a TCM-ADO synthesis to chart the field\u2019s intellectual structure. Clusters emerge around learning, synthesis, health, and validation research. The analysis exposes persistent gaps \u2014 above all, longitudinal evidence on motivational internalisation and cultural breadth of samples. The review anchors a research programme on need-supportive gamification design and identifies where empirical work is most needed. (Currently under review at Computers in Human Behavior \u2014 reuse only where duplicate-submission rules allow, e.g. as a conference talk.)",
  keywords:["bibliometric", "literature review", "meta-analysis", "systematic review", "research synthesis"]},
 {w:2,label:"W2 \u00b7 Test the mechanism",short:"Structured Autonomy with Dialogue Scaffolding \u2014 30-day sprint RCT (RQ2)",tag:"launches Oct 2026",tagCls:"warn",desc:"Two-arm RCT on the Authority\u2013Autonomy\u2013Dialogue architecture; Day 0/10/20/30 measures; SEM + mediation. NO RESULTS until the Dec 2026 analysis \u2014 nothing may be claimed as findings before then.",matchNote:"Results arrive after the Dec 2026 analysis \u2014 venues with earlier deadlines can only take the framework/WIP version, never findings.",
  authors:"Deepu S. Nath et al.",title:"Structured Autonomy with Dialogue Scaffolding: A Framework and Randomized Controlled Study Design for Motivation and Completion in 30-Day Self-Directed Learning Sprints",
  abs:"Self-directed learning environments promise autonomy but frequently fail to sustain engagement: learners begin projects with enthusiasm and abandon them when structure, feedback, and accountability are absent. This work-in-progress paper presents a conceptual framework \u2014 Structured Autonomy with Dialogue Scaffolding \u2014 and the design of a randomized controlled study testing it within Mument, a 30-day self-directed project sprint on the \u00b5Learn peer-learning platform in Kerala, India. The framework integrates Self-Determination Theory and Social Cognitive Theory through an Authority\u2013Autonomy\u2013Dialogue (AAD) architecture: authority as competence structure (weekly checkpoints, karma-point feedback, a culminating expert pitch), autonomy as goal ownership (self-selected deliverables, methods, and pacing), and dialogue as relational scaffolding (expert office hours, structured peer feedback, daily public updates). Seven hypotheses specify a mediation model in which the intervention enhances satisfaction of the basic psychological needs; competence satisfaction builds domain-specific self-efficacy; and self-efficacy drives behavioral engagement, sprint completion, and deliverable quality \u2014 while need frustration predicts dropout and disengagement. The planned two-arm trial (target N \u2265 120 across campuses) holds autonomy constant in both conditions and manipulates structure and dialogue, with self-efficacy measured at four time points and pathways tested through structural equation modeling with bootstrapped mediation analysis. Feedback is invited on the framework and study design. [NO RESULTS EXIST until the Dec 2026 analysis \u2014 never add findings claims.]",
  keywords:["self-directed", "autonomy", "experiment", "e-learning", "online learning", "engineering education", "educational technology", "motivation"]},
 {w:3,label:"W3 \u00b7 Critique the system",short:"3C paper \u2014 Complacency, Competency, Commercialisation intent (RQ3)",tag:"submission-ready",tagCls:"good",desc:"How compliance-oriented, standardised, controlling structures frustrate autonomy, competence and relatedness (survey n=142, Kerala context). Targets: PAN-IIM WMC 2026, Higher Education for the Future (SAGE), IHERC 2026.",matchNote:"Higher-education policy & management audience \u2014 India management academia and higher-ed policy journals, not the EdTech circuit.",
  authors:"Jayasankar Prasad, Nidhi M B, and Deepu S. Nath",title:"A Practitioner\u2019s Framework for Analysing the Systemic Complacencies in Higher Education Institutions with Reference to Kerala",
  abs:"This work investigates the prevalent issue of complacency in the higher education system within the context of India. Complacency \u2014 characterized by a lack of innovation, adaptability, and responsiveness to changing educational needs \u2014 poses significant challenges to the quality and effectiveness of higher education institutions (HEIs). The paper reviews existing issues from a practitioner\u2019s viewpoint and evaluates them empirically through a survey of 142 respondents from different areas of education. The dimensions of complacency in Indian higher education, including institutional inertia, resistance to change, and stagnation in pedagogical approaches and governance, are explored. Practitioner insights are consolidated into a conceptual model of systemic complacency \u2014 the 3C framework of Complacency, Competency, and Commercialisation intent \u2014 together with approaches to mitigate complacency and foster continuous improvement and innovation, with particular reference to the Kerala context. The findings recommend organizational restructuring, faculty development with industry interface, and curriculum reforms leveraging technological advancement.",
  keywords:["higher education", "policy", "governance", "management", "complacency", "commercialisation", "institution"]},
 {w:4,label:"W4 \u00b7 Study the practice",short:"\u00b5Learn case study \u2014 gamification as need-supportive scaffolding (RQ4)",tag:"data from Sep 2026",tagCls:"warn",desc:"40 participants (success stories + randomly picked dropout cases): what distinguishes sustained contributors from disengagers. Questionnaire in progress.",matchNote:"Data from Sep 2026. Peer-learning, CSCL, and gamification venues; case-study-friendly journals.",
  authors:"Deepu S. Nath et al.",title:"Gamification as Scaffolding for Purpose-Directed Autonomy: A Case Study of the \u00b5Learn Peer-Learning Community",
  abs:"Large-scale peer-learning communities promise self-directed growth, yet little is known about why some members become sustained contributors while others disengage. This case study examines \u00b5Learn \u2014 a Kerala-based peer-learning ecosystem connecting 35,000+ students with industry, academia, and government \u2014 through the lens of Self-Determination Theory, asking how its gamification and community mechanisms (interest-group choice, proof-of-work challenges, karma and recognition, learning circles and mentors, leadership roles) support or frustrate basic psychological needs and shape motivational internalisation. The design compares approximately 40 members \u2014 documented success stories and randomly selected dropout cases \u2014 using questionnaires and platform records, with data collection from September 2026. The expected contribution is a practitioner-grounded model of need-supportive gamification for organisations. [Work in progress: design stage \u2014 no findings yet.]",
  keywords:["peer learning", "community", "case study", "gamification", "collaborative", "cscl", "informal learning"]}
 ]
};
